### ISSUE TITLE
Guiding principles

### ISSUE THREAD

**Issue by keawade** [whiteboards/converse#5]
What central principles do we want to guide development? These should be concise statements that reflect the core ideals we want to promote.

If proposed features don't fit these themes, they don't get merged. If features are neutral or borderline, we should discuss them on a case by case basis.

**Comment by keawade** [comment]
My own suggestions are
- _Privacy_
  - Data is volunteered, not required (Other than email and user name, obviously)
  - We never release volunteered data to third parties
  - We should be extremely careful how we handle that data internally
- _Discussion_
  - I'd love for this to be a place for thought provoking discussion rather than "OMG CUTE PUPPY" (or kittens, haha)
  - Maybe build in features to encourage citing sources? I'm not quite sure how to approach this idea

**Comment by NathanBland** [comment]
My core idea is that it isn't a shoutbox.

To me it's more about finding out the information you want than what is
already provided.

I can see the value of what you are proposing with sources, though I feel
like that may be a bit different from what I am envisioning.

Thought provoking is good, but again most people just want to know what
their friends are up to.

My core design principle is privacy first. Simplify always.

**Comment by keawade** [comment]
I asked a friend for input and their take on what's wrong with traditional social media was similar but added an interesting angle (emphasis added):

> Audience specificity mostly. I have _different kinds of conversations with different kinds of friends_. On fb I'm always shouting to the whole world

**Comment by keawade** [comment]
I'm not really sure how we could even begin to combat this, but [this sort of thing](https://www.washingtonpost.com/news/the-intersect/wp/2015/10/30/what-was-fake-on-the-internet-this-week-why-do-we-even-bother-honestly/) really worries me with the way traditional social media works.

If you're interested, [this article](https://www.washingtonpost.com/news/the-intersect/wp/2015/12/18/what-was-fake-on-the-internet-this-week-why-this-is-the-final-column/) is the final article in the column and discusses why they're ending it. Spoiler: It's closely related.

**Comment by crodeheaver** [comment]
Well I think the first article kinda says it all. We can't combat that. Like it said, the two groups of people simply don't overlap and you can't exactly change their groups of friends. And even when they do overlap, the theorists will reject it anyway.

Though on that note, I think a more practical question is not how we should combat it, but IF we should combat it. If we start policing our users, it's an intrusion. Even if we add something like a way to provide sources, people will only add shitty sources and call it proof.

As a matter of principle, like Nathan was saying, privacy is the most important rule of thumb. And with privacy is the right to do/say/believe what you wish. It's not our business to combat peoples ignorance, even if it bothers us.

**Comment by crodeheaver** [comment]
Plus this is Nathan's baby and I feel like he's going for something more simple and a slightly different direction. Though I could be wrong. Haha

**Comment by keawade** [comment]
What I'm trying to point out is that traditional social networks only add to the problem by allowing users to segregate themselves so easily. It's extremely easy to build an echo chamber of reinforcing bullshit.

That's the problem that I think we might be able to address, but I'm not sure how to approach it. We need ethical ways to encourage users to branch out beyond their echo chamber or ways to discourage the construction of echo chambers in the first place.

**Comment by crodeheaver** [comment]
It depends on what we're going for here then. If it's facebook style where it's a friend thing (which is my understanding) or a reddit thing where everyone is open to everyone.

If it's a facebook style thing, then you can encourage people to make new friends with differing views. If it's a reddit style thing, then it leaves things open for a significantly different approach to things.

Have you guys had a get together to actually discuss specifics about what's being made or is everyone just kinda coding what they think is being made?

**Comment by keawade** [comment]
So far I haven't worked on anything that gets into that functionality yet. This issue page has been the entire discussion so far.

**Comment by crodeheaver** [comment]
Well then, let's get @NathanBland in here to clarify. I think it's a little early to discuss combating anything when we don't even know what we're going for in the first place. lol.

@NathanBland lead us oh wise and benevolent one!

**Comment by NathanBland** [comment]
Sorry for not chiming in on this sooner guys, was not near a keyboard all weekend.

To put it simply, this isn't a problem for this platform. That's part of the whole point actually. I'm sick of traditional social media, because I will get junk like this that shows up in my news feed. Converse, or whatever it ends up being called eventually, is about actually finding out what you want to from your friends. It's about asking for information that you seek from your friends. I'll list a few options below that I would love to see as default options.

## Questions you should be able to ask your friends:
- What are you up to?
  - This is the simplest form, and the closest we should get to a "status update". It can be looked at like a general inquiry.
- What are you listening to? 
  - Should give the user an option to either drop in a URL (youtube link, viemo, etc) or just a title and artist. We should then go query an API like youtube, soundcloud, etc. and return to the individual(s) that asked the original response from the user, as well as an integrated search list of "embedded" results.
- What are you reading?
  - This is one of two options that I guess allow for people to post junk like what @keawade mentioned above. The reason this isn't a problem is that it will only show up to those who ask for it. While I believe there are some people who would directly link their friends to this kind of crap, I also believe the amount of people who would directly respond to friends with this, as opposed to just updating their feed, is dramatically lower. 
- What are you watching?
  - This more closely aligns with the music option above in terms of what we should do for processing the content that the user includes, though like the "what are you reading" a most likely option for response is a link. 
- Where are you/where are you headed?
  - Kind of like a built in `glympse` or google maps share location, not sure how many people actually care about this, but it would be nice to have it as an option.
- What are you....?
  - This is a custom question that I think should be an option as well. People may want to know something more specific than the options we have above. I'm also going to use this as a segue to privacy that @crodeheaver also brought up, as I believe this question requires a different level.

## Our Content Model and User Flow

As briefly mentioned [already in this issue](#issuecomment-162265653) we are not a typical bit of social media. At least that is not my vision. Listed below is what I think Converse should be all about, I'm open to discussion on this, but this is what I believe we should be.

### NOT a shoutbox, or endless stream
- We are not built to show endless streams of updates from people, or content shared. We are a different format.

### We are more "real time"
- Updates appear when asked for, not before, not after.

This is the core of what we should be. When talking about using our system, we should always start with "as a user". So, let me explain:
- As a user, I should be able to ask my select friends questions (see above) and get updated information that I asked for.
- As a user, I should see my friends requests for information and be able to respond to that in a meaningful way. 
- As a user, if I choose, I should be able to know who is asking for what information.
  - If I am ok with the default setting of "x(number) of your friends asked for an update" then great, however, if I want to know who is asking for what, I should have that option: "Keith, Colby, & Jim-bob want to know what you are doing next saturday"
- As a user, I should be able to see what others are asking my friends: "Colby has 3 friends that are wanting to know what he is listening to"
  - I should be able to add my name/number (x number of friends/names of friends) to this easily. 
- As a user, I should not be given stale information.
  - If I ask for an update, you can show me what their most recent update was, but tell me how old it is, and notify me when they give an updated response: "The last time someone asked Keith what he was watching, he said he was watching star-wars. That was 4 days ago, asking him for an update."

This should get us started, and honestly there is a lot of work to make that simple list come to life.

The user's contact card can be used to show a list of questions that you can ask, and that have been asked, while a "stream" on the right side where the hard-coded cards are, can deliver updates as they come in. **We should never show information older than 10 hours here unless asked for it.** 

Sorry for the wall of text, like I said I'm more than open to input on this, but you asked haha.

**Comment by crodeheaver** [comment]
The more info the better, in my opinion. I think it's important to have a unified end goal in everyone's mind from start to finish so that the end product can become more refined over time, but with the same guiding principles through out.

**Comment by crodeheaver** [comment]
I mean, if we want to discuss what we're making, now is the time, not later when we'll have to start making changes to the structure of the project.

**Comment by NathanBland** [comment]
I agree with you, and my opinions and vision of what this should be are reflected in the comment above. Can I ask what your thoughts are here @crodeheaver ? (I want @keawade's thoughts too, but I don't think he is around right now.)

**Comment by NathanBland** [comment]
I guess my main thing is that the world doesn't need another twitter or facebook. Those services already exist, have multiple clones, and are established. I want to create something different.

**Comment by keawade** [comment]
I think my main questions are along the lines of how do we get users to consistently interact that deeply?

For example, Reddit allows for a lot of interactivity if users want to, but the majority of users just want to read/see cool things. If they have to request every piece of data, that could end up being a lot of work for not much content.

**Comment by crodeheaver** [comment]
My thoughts are that I'm happy to build whatever. haha.

I could already see a disparity in what everyone thought was being built, so  I thought it would be good to get on the same page.

I think mostly we need to delve out the details of how we're going about things. Like what Keith just said about getting users to consistently interact that deeply.

**Comment by crodeheaver** [comment]
What kind of content are we passing around, is the question. Are we focused on just day to day things or are we passing around interesting articles and ideas? Who and what are we catering to?

**Comment by crodeheaver** [comment]
Are we looking to spark ideas and discussion or just passing around details of what's happening in life?

**Comment by NathanBland** [comment]
That's a good question, in my mind this isn't a service I _want_ people to spend buckets of time on. I want them to use it if they want to know something, and get off of it when they are done. Interactions should be quick, and simple. 

@crodeheaver, thanks for bringing this up though, as it is a discussion that needed to happen before we go further. 

@keawade, I sort of answered your question at the of this response, but let me elaborate a bit more. Think of how we use hangouts for `team super awesome`, that isn't something that we really interact with in a deep way, but something we do show things to people we think might actually be interested in. I'm way more likely to put something interesting into that conversation than I am on to facebook, because I think the people in it might actually gain a benefit from it.

**Comment by NathanBland** [comment]
@crodeheaver in my mind, this is not a great format for sparking ideas and discussion, as if we were going for that format we would be looking at something similar to reddit. It's a bit like day to day things, but a bit more in depth.

**Comment by crodeheaver** [comment]
kk.  That's what I thought, but I wanted it to be clarified.

**Comment by NathanBland** [comment]
_If_ we wanted to, we could give the options to ingrate with services like facebook, twitter, reddit, soundcloud, youtube, etc. on a user's profile to help aggregate this information, but to me this should never be directly displayed on that user's friend's feeds (if that makes sense). What this would do is allow the user being asked for updates to have easier access to the kind of information they are being asked to share. I'm still not sure how I feel about this though, or if it is actually a good idea.

**Comment by keawade** [comment]
On the one hand, I'm primarily interested in this project for the experience of building it. On the other hand, @NathanBland mentioned fixing the problems of Facebook and I might have gotten carried away with dreams of fixing my own list of problems, haha.

I'm down for building whatever, but if I've got an opportunity to point us in a particular direction I'd like to aim more towards sharing interesting ideas and tackling echo chamber issues.

**Comment by NathanBland** [comment]
@crodeheaver also, more information on what kind of information I think should be passed around is listed in the [issue above](#issuecomment-166335404).

@keawade I see what you are saying, and my point is this, we are the anti-thesis of facebook. We aren't an echo chamber by design in that we don't broacast things to everyone without knowing if they care or not. Facebook is spending a _ton_ of man power right now trying to create a solution to the problem that has become their newsfeeds. I simply want to bypass that issue.

**Comment by NathanBland** [comment]
I'm fine with creating some sort of system that allows people to predefine updates as well. So that if someone asks for a status update, you can have something set like: "If one of my friends asks what I'm listening to, share this youtube playlist with them" kind of a thing, but I _do not_ want this place that becomes a "oh hey I think this is an awesome neato idea, even though its full of crap, please read my article". We don't have the ability to solve this problem, so we are creating a way to change the way people interact.

**Comment by NathanBland** [comment]
When I see friends in person, I don't just walk up to them, stand there blankly staring at them, and wait for them to shout ideas at me (facebook), I engage them, I ask questions, even if it is just small talk. This can lead to deeper (see custom questions) interaction if I want it, but doesn't have to. Both people feel engaged, and it keeps the friends pool smaller, instead of this "I have 150+ friends, 10 of which I care about interacting with, and I wonder why my newsfeed is always full of crap I don't care about".

**Comment by keawade** [comment]
If we're focusing on sharing ideas, the echo chamber problem is significant. However, I think you're right that this would work better for keeping up with close friends, etc. That model bypasses the echo chamber problem.

I think we should note that if the data being shared here is supposed to be more personal in nature, how we handle privacy becomes much more important.

**Comment by keawade** [comment]
Here's my current summary of our vision:

### Privacy
- Privacy, privacy, privacy. Privacy.
- We don't purposefully release any user data.

### Content
- Content for users is defined by what they request, not by what is shouted in their vicinity.

**Comment by NathanBland** [comment]
I agree completely, here are my suggestions for privacy:
- We provide no option for "global" updates. You have to be friends with someone to share.
- By default, a request for information will only show the number of friends asking for it.
  - "2 of your friends want to know what you are reading"
- Additional options should include
  - Knowing who is asking for updates:
  - Person A has privacy settings on "what are you listening to?" set to only allow requests from people who share their name". When person B asks for an update, we should alert them "Person A requires you to share your name when asking this question, continue?" 
  - I should be able to disable certain questions from being asked.

**Comment by keawade** [comment]
I think the main thing so far for content is that this platform will only work with groups of engaged individuals. I think it would work well for our group of friends but the service would likely never really take off elsewhere.

**Comment by crodeheaver** [comment]
Another thing is, how do you keep this from essentially becoming a sophisticated chat box? Basically, to what level are we going to filter down content that gets passed between people?

**Comment by keawade** [comment]
@crodeheaver I kind of like the idea of just building a sophisticated chat box...

**Comment by NathanBland** [comment]
@keawade Look at how many people comment on things on facebook, youtube, reddit, etc. Engagement isn't the problem, streams of crap are. People want to interact or those services wouldn't exist. 

@crodeheaver We are eliminating group think for one thing. We show you how many people are asking for something, but we don't tell you who they are specifically unless you demand to know for your updates. There isn't a "flow" for this to be a chat-box, aka no "threaded" streams.

**Comment by crodeheaver** [comment]
Problem is, those streams of crap are generated by people too. Despite what we like to believe, there are actually people out there that feed off of all the crap we find on our steams. lol. If there weren't it wouldn't be there.

**Comment by NathanBland** [comment]
You are right of course, though I mostly think that's because of how easy sites like facebook have made it to share that. Every site you go to has a "share on facebook" button. No thought is required for it.

**Comment by keawade** [comment]
@crodeheaver This. FB has engagement across a mountain of vacuous crap generated by 300-500 friends per user. If we've narrowed to 10-30 friends, I think we'll have difficulty having that level of engagement.

**Comment by crodeheaver** [comment]
@keawade agreed.

@NathanBland I'm slowly getting a picture of an inverted twitter with less ability to abuse it by spamming crap at people and more focused on good friends instead of anyone willing to read the nonsense you're throwing out there.

**Comment by keawade** [comment]
An inverted twitter fits my idea of what we're talking about.

Maybe it would work to have a "feed" (Using that term loosely) of _only_ life events.

EDIT: "feed" is the wrong word. More of just a timeline for each user.

**Comment by crodeheaver** [comment]
The problem with a feed is that it directly goes against the idea of this not being a shout box. At best it would be more like a history of questions and responses you've asked. Or something like that. I think....

**Comment by keawade** [comment]
It just doesn't make sense to me that if I wanted to know when Jora's anniversary was, I'd have to send a request for that data, even though we're already friends on the service. Shouldn't I just be able to pop over to some sort of timeline and view those sort of public life events? Users should be able to choose what events they wished to make available to public, friends, etc of course.

**Comment by NathanBland** [comment]
An inverted twitter is a good analogy for what I see this as. 

@crodeheaver A "feed" in our sense of the word would be like you said, a list of questions you asked, and the responses given to it. "3 hours ago you asked Keith what he was listening to, the last time someone asked his answer was xxxx, he hasn't responded to your question yet." In this way we provide meaningful information without generating "crap streams" that the user hasn't asked for. These streams, like I mentioned above, should be limited to 10 hours or so, or better yet, be able to be set by a user. "No updates in the last 5 hours, try asking a question" 

@keawade if we get into relationship type things, I see this being more of a profile setting than something that is declared via a feed, which we could then stream to users if they asked for it, but not really pester them with it either. 

"User A sets their relationship status, and in the case you mentioned, anniversary date, this is then listed on their profile. User B asks for an update and we feed them that information back." 

User A should have the option to set this question as a "non updating" type question, meaning that until they change the option set in their profile, there will not be a change. I think for certain questions, this would actually be good to have as a default option.

**Comment by NathanBland** [comment]
I apologize for being sort of a black-box of information regarding some of this stuff. I have answers for most of these questions rattling around in my head, but I haven't really expressed them. Thanks for bringing these questions up so we can get it out in the open.

**Comment by NathanBland** [comment]
Also, @keawade @crodeheaver please keep asking and giving feedback so we can get a concise picture of what we are doing.
